version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.3
    ports:
      - 5601:5601
    environment:
      - "xpack.security.enabled=false"
  boardgames:
    build:
      context: .
      dockerfile: Dockerfile.App
    image: boardgames-website
    environment:
      - ELASTICSEARCH_INDEX=http://elasticsearch:9200/games
    ports:
      - 5000:5000
    volumes:
      - ./app:/app
    restart: unless-stopped
    environment:
      - ELASTICSEARCH_INDEX=http://elasticsearch:9200/games
      - ELASTIC_APM_SERVICE_NAME=boardgames
      - ELASTIC_APM_SERVER_URL=http://apm:8200
      - ELASTIC_APM_DEBUG=True
  apm:
    image: docker.elastic.co/apm/apm-server:6.2.3
    ports:
      - 8200:8200
    volumes:
      - ./apm/apm-server.yml:/usr/share/apm-server/apm-server.yml
volumes:
  esdata1:
    driver: local