version: '3'
services:
  logstash:
    image: logstash
    build:
      context: .
      dockerfile: LogstashDockerfile
    ports:
      - 9600:9600
    volumes:
      - ./rss/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    restart: always
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.3
    ports:
      - 5601:5601
  rss:
    build:
      context: .
      dockerfile: RSSDockerfile
    image: rss-website
    environment:
      - ELASTICSEARCH_INDEX=http://elasticsearch:9200/podcasts
      - xpack.security.enabled=false
    ports:
      - 5001:5000
    volumes:
      - ./rss:/app
    restart: always
volumes:
  esdata1:
    driver: local