version: '3'
services:
  logstash:
    image: logstash
    build:
      context: .
      dockerfile: Dockerfile.Logstash
    depends_on:
      - elasticsearch
    ports:
      - 9600:9600
    restart: always
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
      - ./elasticsearch/synonym.txt:/usr/share/elasticsearch/config/analysis/synonym.txt
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.3
    ports:
      - 5601:5601
  podcasts:
    build:
      context: .
      dockerfile: Dockerfile.App
    depends_on:
      - elasticsearch
    image: podcasts-app
    environment:
      - ELASTICSEARCH_INDEX=http://elasticsearch:9200/podcasts
      - ELASTIC_APM_SERVICE_NAME=podcasts
      - ELASTIC_APM_SERVER_URL=http://apm:8200
      - ELASTIC_APM_DEBUG=True
    ports:
      - 5000:5000
    volumes:
      - ./app:/app
    restart: always
  apm:
    image: apm
    build:
      context: .
      dockerfile: Dockerfile.Apm
    depends_on:
      - elasticsearch
    ports:
      - 8200:8200
volumes:
  esdata1:
    driver: local