apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: logstash
  name: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - image: gcr.io/macro-dolphin-137214/logstash
        name: logstash
        volumeMounts:
        - name: logstash-configmap
          mountPath: /usr/share/logstash/pipeline/
      volumes:
      - name: logstash-configmap
        configMap:
          name: logstash
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash
  namespace: podcasts
data:
  logstash.conf: |
    input {
  
      rss {
        id => "6figuredev"
        url => "http://6figuredev.com/feed/podcast"
        interval => 7200
            tags => ["6 Figure Developer"]
      }

      rss {
        id => "applicationsecurityweekly"
        url => "http://aswaudio.swsgtv.libsynpro.com/rss"
        interval => 7200
            tags => ["Application Security Weekly"]
      }

      rss {
        id => "angular air"
        url => "http://audio.angularair.com/feed/"
        interval => 7200
            tags => ["Angular Air"]
      }

      rss {
        id => "codecrush"
        url => "https://rss.simplecast.com/podcasts/3295/rss"
        interval => 7200
            tags => ["Code Crush"]
      }

      rss {
        id => "codingblocks"
        url => "http://codingblocks.libsyn.com/rss"
        interval => 7200
            tags => ["Coding Blocks"]
      }

      rss {
        id => "completedeveloper"
        url => "https://completedeveloperpodcast.com/feed/podcast/"
        interval => 7200
            tags => ["The Complete Developer Podcast"]
      }

      rss {
        id => "cynicaldeveloper"
        url => "https://cynicaldeveloper.com/feed/podcast/"
        interval => 7200
            tags => ["The Cynical Developer"]
      }

      rss {
        id => "eatsleepcode"
        url => "http://feeds.feedburner.com/esc-podcast"
        interval => 7200
            tags => ["Eat Sleep Code Podcast"]
      }

      rss {
        id => "impostorsyndrome"
        url => "https://impostor-syndrome.squarespace.com/episodes?format=rss"
        interval => 7200
            tags => ["Impostor Syndrome"]
      }

      rss {
        id => "juniordevtoolbox"
        url => "https://juniordevelopertoolbox.com/feed/podcast/"
        interval => 7200
            tags => ["Junior Developer Podcast"]
      }

      rss {
        id => "msdevshow"
        url => "http://msdevshow.libsyn.com/rss"
        interval => 7200
            tags => ["MS Dev Show"]
      }

      rss {
        id => "programingthrowdown"
        url => "http://feeds.feedburner.com/ProgrammingThrowdown"
        interval => 7200
            tags => ["Programming Throwdown"]
      }

      rss {
        id => "weeklydevtips"
        url => "https://rss.simplecast.com/podcasts/3342/rss"
        interval => 7200
            tags => ["Weekly Dev Tips"]
      }
      
    }

    filter {}

    output {

      elasticsearch {
        action => "index"
        index => "podcasts"
        hosts => "elasticsearch:9200"
        document_id => "%{[link]}"
        workers => 1
      }

    }

  
