apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: logstash
  name: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - image: gcr.io/macro-dolphin-137214/logstash
        name: logstash